create database if not exists krazymlbb;

use krazymlbb;

CREATE TABLE if not exists `hero` (
  `id` int(11) NOT NULL,
  `name` varchar(256) NOT NULL,
  `class` varchar(256) NOT NULL,
  `battlepoint_cost` bigint(20) NOT NULL,
  `diamond_cost` int(11) NOT NULL,
  `movement_speed` int(11) NOT NULL,
  `physical_attack` int(11) NOT NULL,
  `physical_defense` int(11) NOT NULL,
  `magic_power` int(11) NOT NULL,
  `armor` int(11) NOT NULL,
  `magic_resistance` int(11) NOT NULL,
  `hp` int(11) NOT NULL,
  `mana` int(11) NOT NULL,
  `attack_speed` float NOT NULL,
  `hp_regen_rate` int(11) NOT NULL,
  `mana_regen_rate` int(11) NOT NULL,
  `img_profile_url` varchar(1000) NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into hero values (1, "Akai", "Fighter", 32000, 599, 260, 115, 24, 0, 24, 10, 2769, 422, 0.85, 42, 12, "http://krazywoman.com/krazymlbb/images/akai.jpg", "A clumsy panda from a far away Eastern village dreamt every night of becoming a mighty warrior. Akai was fat and clumsy even for panda standards and most people said that all he's good for was rolling round. Howeverthis never fazed Akaias he trained dailyhoping to one day achieve his dreams of becoming a respected warrior. His friends mocked himhis parents discouraged him but Akai persisted. Soon one daya mysterious old monk noticed Akai\'s persistence and took him under his guidance. Akai flourished under the training of the monkmastering the arts of the flail. He is now ready to get onto the world stage and prove that he is a worthy member of the martial arts world!");

insert into hero values (2, "Aldous", "Fighter", 32000, 599, 260, 129, 22, 0, 22, 10, 2718, 405, 0.84, 45, 18, "http://krazywoman.com/krazymlbb/images/aldous.png", "Legends from the Land Of Dawn say that the Western Desert's Minoan Kingdom possess a mysterious labyrinth. In the maze is a statue of giant Minotaur (Strange half-bull, half-human creatures), which the people consider to be the mecca of the Minoan Kingdom. Some say that there is a group of contractors who guard the entire maze, somewhere inside which, lies the Twilight Orb. It is also what led to the downfall of the kingdom, because, with the fortune powers from the Twillight Orb, the Kingdom produced a lot of precious jades, which brought the Minoan people great wealth. Very quickly, though, the entire kingdom was lost in the intoxicating allure of gold and riches. Even many of the contractors.");

insert into hero values (3, "Alpha", "Fighter", 32000, 599, 260, 121, 20, 0, 0, 10, 2646, 453, 0.92, 39, 16, "http://krazywoman.com/krazymlbb/images/alpha.png", "Alpha is another creation of Laboratory 1718 after Saber left. The evil-turned scientist's got a new idea from a famous sci-fi movie that had been trending in the Land of Dawn. Using human bodies as biological material and space meteorolite as metal skeletons, they created powerful twins. Alpha and Beta, also known as 'Flesh Weapon', they were capable of utilizing a supernatural power that was ubiquitous but very mysterious. However, the twins had their consciousness awakened, since they were born, and refused to become killing machines. Getting help from Saber, they escaped from the alter-world. However, on their way of escape, the made man Beta's core was destroyed, due to the explosion of a frag grenade, launched by the mad scientiss. All that Alpha could retrieve, was one of Beta's dislodged metal arm. After escaping from laboratory-1718, along with Saber, they arrived at the Land of Dawn and with the help of master machinist Rooney, Beta was transformed into his current fighter-air drone form and now Beta keeps company with Alpha, together as the ultimate weapon pair.
");

insert into hero values (4, "Bruno", "Marksman", 15000, 399, 240, 128, 17, 0, 0, 10, 2522, 439, 0.85, 30, 15, "http://krazywoman.com/krazymlbb/images/bruno.png", "Growing up in the slums, Bruno was always thinner and much more frail than his peers. However, these circumstances never stopped him from having a courageous heart, filled with freedom. Bruno's kindness and integrity were his greatest traits. He was also known to have much improved leg strength and efficient kicking techniques, which had been well exercised, through him playing local soccer. Thus, he remained proud of his performances. However, Bruno used these techniques to not only defeat lots and lots of malicious soccer opponents, but also help his villagers, as well.");

insert into hero values (5, "Irithel", "Marksman", 32000, 599, 250, 110, 17, 0, 0, 10, 2540, 438, 0.83, 35, 15, "http://krazywoman.com/krazymlbb/images/irithel-mobile-legends.png", "Irithel was abandoned as a child, in the jungle by her parents. Under the guidance of the God of the Jungle, a female smilodon that had just given birth, adopted her. Under the protection of the mother smilodon, the little smilodon Leo and Irithel learned to hunt, survive and adapt - she grew up like an animal. During a territorial fight against a pack of jaguars, the mother smilodon was badly wounded. When Irithel and her brother Leo went into town for help, they were referred to as smilodon children and were captured by a slave trader. When the cat elf mage - Nana passed by, she couldn't bear to watch them get beaten by the slave trader, so she used her magical strength to save these 2 poor children from the slave trader. With the help of Nana, who was still younger than Irithel, she learned to speak like a human and also learned to fight, using ranged weapons.");

insert into hero values (6, "Granger", "Marksman", 32000, 599, 240, 125, 15, 0, 0, 10, 2490, 0, 0.82, 27, 0, "https://gamerhub-uploads.s3.us-west-1.amazonaws.com/26dffdfb76a1428294e5611208172215.png", "Granger was orphaned during the war between the Moniyan Empire and the Southern Monsters. He was picked up by the Imperial Army, and then sent to the Monastery of Light. Similar to all orphans, Granger was silent and isolated. He never showed much feelings through his cold eyes. However, since a young age, Granger greatly enjoyed music and only when the melody of violins, emerged from the monastery would Granger show any interest, getting lost until the music ended. During their growth, every orphan in the monastery has two options for their future, on adulthood: to be a demon hunter, living by completing the secret and dangerous tasks assigned by the Empire, or to be a servant of the monastery, doing the cleaning and washing for a lifetime. To everyone's surprise, Granger choose guns and violins at the same time, meaning that he would choose both options.");

insert into hero values (7, "Gatotkaca", "Tank", 32000, 599, 260, 120, 0, 0, 20, 10, 2709, 440, 0.82, 42, 12, "http://krazywoman.com/krazymlbb/images/gatotkaca-mobile-legends.png", "Gatotkaca 'The Man of Steel' was the son of Bima and Arimbi from the Arcapada universe. Since his childhood, Gatotkaca has been a champion of Gods, fighting vicious enemies in his homeland. Once lost and beaten near death, Gatotkaca rose as a mighty warrior from the Pandava clan who possessed supernatural powers, which he had recieved from the ultimate training inside the cauldron of heaven, Candradimuka. With his Antakusuma armor and Brajamusti-Brajadenta twin gauntlet, he can sore across the skies like lightning and hunt down his enemies, the furious Ashuras, and their king, Martis. Gatotkaca, the Knight of Priggadani, has ever since been a symbol of bravery and devotion.");

insert into hero values (8, "Khufra", "Tank", 32000, 599, 255, 117, 19, 0, 0, 0, 2709, 460, 0.79, 47, 15, "http://krazywoman.com/krazymlbb/images/khufra.png", "In the far reaches of the Western Desert, an ancient city lays hidden among the sands. Despite ages passing by, the desert sands were unable to devour this city, which stands proud and majestic in a sea of emptiness. Scholars of antiquities have long spoke of this fabled city, whose most infamous ruler was none other than Khufra. Khufra was a greedy ruler, colder than ice, and avaricious to limitless extents. In order to satisfy his personal desire to rule, he led the powerful army of Arnak to invade the city to conquer the Western Desert. Tirelessly, Khufra expanded his domain and riches beyond compare. Unfortunately, the Minoan Empire proved to be too difficult of a foe to conquer.");

insert into hero values (9, "Minotaur", "Tank", 15000, 399, 260, 123, 23, 0, 0, 10, 2759, 0, 0.73, 44, 0, "http://krazywoman.com/krazymlbb/images/minotaur.jpg", "The young Minotaur, was actually the first born of Minos, the arrogant ruler of the Minoan Kingdom, and was originally named Asterion, on his birth. But unfortunately he was abandoned by his parents at a young age, since they considered him to be an embarrassment due to his unusual bull-like features. As such, Asterion grew up alone, not knowing his name or who he was. Living such a life, Asterion soon took interest in local brawl fights with other Minotaurs. Nourishing his combat skills in a somewhat unique way, he soon became known as 'The Minotaur', the most talented and powerful one in the kingdom, admired and worshiped by other ones, up until he was defeated by a youth from a far-off land.");

insert into hero values (10, "Esmeralda", "Mage", 32000, 599, 240, 114, 21, 0, 0, 10, 2573, 502, 0.8, 36, 20, "http://krazywoman.com/krazymlbb/images/esmeralda.png", "After becoming the successor of the astrologers, Esmeralda guards the Starmoon Casket that has been passed down for generations. With the hope of opening it and gaining the mysterious power from the ancient times, Esmeralda leaves off to the Minos Labyrinth to find secrets of the Starmoon Casket. But unfortunately, on her way to the Minos Labyrinth, the ground suddenly shakes and the desert falls into pieces, followed by a black sandstorm. All of a sudden, the Starmoon Casket opens and a stream of mysterious power fills in Esmeralda. Under the protection of the mysterious power, Esmeralda gets no harm and feels old memories flashing back through her mind.");

insert into hero values (11, "Gord", "Mage", 24000, 499, 240, 110, 0, 0, 13, 10, 2478, 570, 0.77, 32, 25, "http://krazywoman.com/krazymlbb/images/gord.jpg", "Gord had always been the living proof of excellence in the Magic academy. He was born into a world of magic, with the gift to manipulate the mystical powers as easily as breathing in air. His love for mystical magic was particularly powerful, which allowed him to master several sophisticated and profound mystic spells at an early age. But this was clearly a double-edged sword, because as Gord grew older, his reliance on mystic magic became more sever, making him increasingly arrogant, over time. Once he stumbled across an Elemental book in the forbidden part of the Academy.");

insert into hero values (12, "Valir", "Mage", 32000, 599, 245, 105, 18, 0, 0, 10, 2516, 495, 0.8, 34, 18, "http://krazywoman.com/krazymlbb/images/valir.jpg", "Legend has it, that at the end of the western desert, there lies a beautiful and rich country. This fabled land, is where Valir comes from. He was known to have been the prince of this country, the son of Flames, the great wielder of fire. The Valley of Winds is a neighbouring kingdom of Fire Throat. Valir's father and the king of Valley of Winds were close friends, since their childhood and so where his son, Vale and Valir. But unfortunately, misjudgment and false conspiracies, led to the death of Flames, which was more painfully from the hands of Vale's father. Valir was there, along with Vale, when his father was murdered. Valir was grieved and he tried to fight the king of wind, but to his surprise, he was knocked off his feets, due to a wind tornado, summoned by his very own friend. Vale painfully, bid goodbye to his best friend, advising him to flea the lands and never come back.");

insert into hero values (13, "Hayabusa", "Assassin", 32000, 599, 260, 117, 0, 0, 0, 10, 2629, 0, 0.85, 37, 0, "http://krazywoman.com/krazymlbb/images/hayabusa.jpg", "Many years ago, the god of the very first ninjas created the Order of the Scarlet Shadow, formed of countless outstanding disciples. Over time, beliefs within the order diverged, and the Scarlet Shadow split into two factions—the Scarlet Sect and the Shadow Sect. The conflict between the two sects gradually intensified, even to the point of drawing swords on one another. In order to avoid bloodshed, the two sects decided that every ten tears they would select the best Scarlet ninja and the best Shadow ninja to duel. The winner would inherit the title 'Scarlet Shadow Grandmaster', under whom the two sects would study according to the ninja code left behind by their god. Ten years ago, a Shadow emerged possessing the kind of exceptional ability one sees only once in a hundred years. Even the Scarlet sect recognized his talent, but as they anticipated the day this Shadow would inherit the Scarlet Shadow title to unite the two sects and resurrect the glory of the Order of the Scarlet Shadow, heinous events transpired that would change the ninja world forever.");

insert into hero values (14, "Gusion", "Assassin", 32000, 599, 260, 119, 18, 0, 0, 10, 2578, 469, 0.89, 39, 16, "http://krazywoman.com/krazymlbb/images/gusion.jpg", "The Paxley family is one of the most powerful, proud and prestigious magic families in the Land of Dawn, and each of it's member is raised to become a mage of the finest order. In their eyes, the path of the magician is the most sacred and noble vocation there is, and all those who brandish a sword in battle are merely considered as insubstantial weaklings and dim-witted fools. Gusion, however, was determined to break the mold. The patriarch's fourth son, Gusion, exhibited a high affinity towards light elements at a very early age, but rather than spend his days with his nose buried in a book studying spells, Gusion would use his control over light to imbue himself with the speed, to run laps of the family estate in mere minutes, and to enchant old ceremonial swords with powerful magical properties of the Holy light. He always believed that the family elders were incurably stubborn and rebelled against their wishes at every opportunity.");

insert into hero values (15, "Helcurt", "Assassin", 32000, 599, 255, 121, 17, 0, 0, 10, 2559, 440, 0.87, 35, 16, "http://krazywoman.com/krazymlbb/images/helcurt-1.jpg", "In the historical records of the Land of Dawn, there was said to be a mysterious race who had sacrificed their souls to the ruler of the Abyss, in exchange for great power. Their bodies were transformed using dark magic, granting them the ability to swallow light and travel through space in the blink of an eye, allowing them to surprise their enemies with deadly sneak attacks. What was most terrifying about them, however, was the concoction of naturally toxic poison stingers emitted from their tails. For those unfortunate enough to come into contact with this poison would soon be saying their last words. However, this is also what caused the ultimate demise of this race. In the annals, the specifics of how this race was wiped out are not made clear, but it is certain that this terrifying race, definitely walked upon the Land of Dawn. Since their extinction, humanity had progressed prosperously.");

insert into hero values (16, "Faramis", "Support", 32000, 599, 260, 222, 36, 0, 0, 10, 3700, 0, 0.94, 39, 19, "https://gamerhub-uploads.s3.us-west-1.amazonaws.com/a6a701d4cf94489a8cada03d62cea6f6.png", "Far from the Moniyan Empire stands an ancient castle. This castle had a glorious history, even comparable to the Moniyan Empire. Unfortunately, the castle collapsed overnight, as if it had suddenly disappeared. It's tall gray walls were covered with dark black vines, which were more horrifying and strange, under the moonlight. The breath of death and the smell of blood made the creature close to this ancient building, shudder and keep away. It seemed that the owner of the castle had set up a trap, waiting for their prey to fall for it. A man wearing a cape of feathers, stood on a distant hill, looking at this deadly castle. He silently whispered the name of the castle, Necrokeep, as he tried to recall the memories of his past, only to be filled with pain all over his body, again. This pain awakened his inner hatred. As the most prominent magician of the time, Faramis was the only survivor of that disaster.");

insert into hero values (17, "Diggie", "Support", 24000, 499, 250, 115, 18, 0, 0, 10, 2351, 490, 0.8, 36, 20, "http://krazywoman.com/krazymlbb/images/diggie.jpg", "Scholars and thinkers from all over the world are known to finally gather at the city of Antoinerei. It is here where the commonly overlooked Diggie lives. Most people hardly give Diggie a second look, perhaphs due to his small frame, but that is until they come upon his surprisigly, exceptional researches in chronoscience. Diggie loves clocks, and he believes that within these little mechanical toys, lies many more secrets that are yet to be discovered. Through, the use of his Time Nest, Diggie can control the flow of time, even having the ability to slow it down, under certain circumstanced. Additionally, he also has the ability to be able to release his friends from the physical shackles of time, taking them along with him. It's better to beware of him, though, because if anyone angers him, they are most likely get a taste of his Hoot Hoot Time Bomb!");

insert into hero values (18, "Estes", "Support", 32000, 499, 240, 120, 13, 0, 0, 10, 2221, 545, 0.8, 36, 18, "http://krazywoman.com/krazymlbb/images/estes-mobile-legends-bang-bang.png", "At the habitat of the Moon elves, somewhere west of the Moonlake, lies the legendary Emerald Woodland, which was the birthplace of the first generation of elves. Every elven king was born in the Tree of Life at the center of the Emerald Woodland. The elven king of the current generation is the unique Estes, who was badly hurt during the second plain war and had to go into deep sleep in the Emerald Woodland. Moon elves lost the guidance from their king ever since that day. When the flames of wars between humans and orcs burned on this peaceful woodland, the young Moonlight Archer - Miya, stood up and gathered the rest of the elves to protect their homeland. However, the dominator of dark abyss is thirsty for more believers and the dark force has been growing stronger in secret. Seduced by the Blood Queen, Alice, some young elves have fallen. The race of moon elves was once again at stake which outraged the great elven king!");

insert into hero values (19, "Guinevere", "Fighter", 32000, 599, 260, 126, 18, 0, 0, 10, 2528, 0, 0.92, 39, 0, "http://krazywoman.com/krazymlbb/images/violet.png", "The Baroque family is one of the few nobles on the Land of Dawn. The most prestigious skill of them - fencing, the family's emblem, discourages countless opponents from even thinking about attacking. In addition, beauty and wisdom are also the most perfect genetic signs of the Baroque family, just like the eternal beauty and love of Violet. WorId-famous as Baroque family's fencing is, young Guinevere doesn't like it at all. Just like other girls, she is naturally fond of gorgeous things. From youth, she was sent to the Magic Academy. Recently, something has been plaguing Guinevere, making her uneasy. It is said that the Paxley nobles who have a very high magical status have proposed marriage to the Baroque family. Guinevere is undoubtedly the most suitable choice and Guinevere‘s father seems to be very willing with the marriage.");

insert into hero values (20, "Claude", "Marksman", 32000, 599, 260, 137, 40, 0, 0, 0, 3443, 755, 0.88, 46, 65, "http://krazywoman.com/krazymlbb/images/claude.png", "If you often go to the tavern, then you must have surely heard of Claude. His story is one of the favorite topics of tipsy travelers – One of the most famous legends in the Land of Dawn. Rumor has it, that this teenager has a special talent for thievery. To Claude, thievery is a form of art from rather than a crime. In fact, Claude would often send his victims, a notice to let them know when he would commit the crime. Much to everyone’s bewilderment, Claude would always succeed in acquiring his targeted object, regardless of how strong or prepared were their rightful owners. Whether if the target is a king’s heavily-guarded treasury, a magic library protected by powerful spells, or an dark fortress filled with the undead – Nothing can stop Claude from taking what he wants. It is said that this young “Thief King” has a mysterious partner in crime. Some say his partner is a beautiful maiden, other’s say it’s his twin brother.");

insert into hero values (21, "Chou", "Fighter", 32000, 499, 260, 121, 23, 0, 0, 10, 2708, 0, 0.88, 39, 0, "http://krazywoman.com/krazymlbb/images/chou.jpg", "Chou was born in a remote, small slumdog in Antoinerei, living a life of the lowest quality. Even then, the tough living environment had never worn away the kindness in Chou's heart. He cared for elders and minors in the slum, with passion. However, with the rise of turmoil and instability in the Land of Dawn, the situation outside had eventually impacted this isolated slum. On an occasion, Chou saved an old monk who was being chased by a mob. He brought him back to the slum and looked after him. In return, the old monk imparted the ancient Asian Kung-Fu skill to Chou and told him that the world needed a real hero to stand up and end the turmoils. After finishing his apprenticeship, Chou swore before the old monk that he would become a real hero. Then, he started his journey to the center of the Land of Dawn without even looking back once. Towards Chou's distant silhouette, the old monk nodded, and drifted away.");

insert into hero values (22, "Grock", "Tank", 32000, 599, 260, 135, 21, 0, 0, 10, 2819, 430, 0.81, 42, 42, "http://krazywoman.com/krazymlbb/images/grock-mobile-legends.png", "Deep within the Rantha mountains, located in the Land of Dawn sits an ancient fortress. Though the owner is unknown, it is rumored that it could be a descendant of the legendary race of Earthen Giants, that once walked the Lands of Dawn. It said that this race is older than the earth itself, having a special affinity for nature, they were able to build deep connections and relations with various beings of nature, especially the Stone Titans. These amiable giants possess rocky skin that is almost impervious to all physical force. Due to their kind nature, they mainly use their physical prowess to keep them away from other creatures and sleep safely. These stony giants love sleeping so much, that they have the ability to hibernate for up to half a dozen years sometimes. As they sleep, it is natural for trees to be grown within their skin and even buildings to be constructed on them. However once they are awakened, it is hard for them to fall asleep again. One day when Grock, one of the strongest of these Stone Titans, awoke, and found himself to be alone, the guardians of the fortress long gone.");

insert into hero values (23, "Natalia", "Assassin", 32000, 599, 260, 121, 18, 0, 0, 10, 2589, 486, 0.8, 35, 16, "http://krazywoman.com/krazymlbb/images/natalia.png", "Natalia was orphaned from the war and she was raised as a little girl by the Monastery of Light. Natalia was trained into becoming one of the Light assassins. This young phenom had risen to become the top assassin for the Monastery, via her outstanding talents. However, on one assassination mission, she failed in her execution, causing her companions to meet with unprecedented disaster and death. Although she managed to escape danger, with Tigreal's help, this was undoubtedly a severe blow to Natalia's pride. To prove herself again, she exiled herself to the outskirts of the land, far from the Moniyan Empire and the Monastery of Light, to carry out more dangerous missions. It is never known who, her target is or where she might strike next. All that people know is that Natalia intends to win back all that she once possessed.");

insert into hero values (24, "Angela", "Support", 32000, 599, 260, 124, 21, 0, 0, 10, 2628, 0, 0.92, 40, 0, "http://krazywoman.com/krazymlbb/images/angela.jpg", "Dr. Baker was one of the co-founders of Laboratory 1718, an institution created with the aim of bringing peace to the world. But as his colleagues, that is, the other scientists fell deeper and deeper into their depraved human weaponization experiments, Dr. Baker felt he had no choice but to leave all this behind and pursue a new project. Renouncing the questionable ethics of human experimentation, he endeavored to create a new kind of lifeform, solely from a mechanical skeleton, puppet strings, and synthetic skin. Finally, a new generation of artificial life was born. Dr. Baker firmly believed that, love and hope were the greatest inventions of mankind. So he programmed the world's most moving stories into the heart of his new creation, transforming her into an android based robot, meant for helping others. One bright morning, Peace Android Prototype 1 awakened from her bed, and Dr. Baker bestowed upon this adorable mechanical angel, the Name Angela. Angela followed Dr. Baker's tutelage, studying hard to understand the world, and hoping to meet the inventor's high expectations.");
